---

- hosts: all
  tasks:
    - name: CephFS Provisioner | Check Go version
      shell: |
        go version
      ignore_errors: yes
      register: go_version_result

    - name: CephFS Provisioner | Check if image exists
      shell: |
        docker image list | grep 'cephfs-provisioner'
      ignore_errors: yes
      register: check_image_result

    - block:
        - name: CephFS Provisioner | Clone repo
          git:
            repo: https://github.com/kubernetes-incubator/external-storage.git
            dest: "~/go/src/github.com/kubernetes-incubator/external-storage"
            version: 4530b2f
            clone: yes
            update: yes
            
        - name: CephFS Provisioner | Build image
          shell: |
            cd ~/go/src/github.com/kubernetes-incubator/external-storage
            REGISTRY=quay.io/kubespray/ VERSION=4530b2f make ceph/cephfs

        - name: CephFS Provisioner | Push image
          docker_image:
            name: quay.io/kubespray/cephfs-provisioner:4530b2f
            push: yes
          retries: 10
